### PR TITLE
Fix figure margins and canonical circuit layouts

### PR DESCRIPTION
**Pull request by rhaps0dy**

### CODE REVIEW

**Comment by ArthurConmy** [comment]
I can't see the points in the main text. Are you okay with this addition?

image

**Comment by rhaps0dy** [comment]
That looks awesome, thank you!

**Comment by rhaps0dy** [comment]
Can we merge this? Just to close it :)

**Comment by ArthurConmy** [comment]
Great @rhaps0dy . I'm merging but want to flag that the `experiments/results/canonical_circuits/ioi` make command didn't complete after 5 minutes. Is this normal? Should we have a warning (or error)?

**Pull request merged**
